### ISSUE TITLE
Adj. Sharpe Ratio returns Ann. Sharpe Ratio

### ISSUE THREAD

**Issue by mhmilo24** [braverock/PortfolioAnalytics#16]
Example:
...  %>% tq_performance(Ra = ACWI, performance_fun = AdjustedSharpeRatio)

Output:

# A tibble: 1 x 1
  `AnnualizedSharpeRatio(Rf=0%)`
                           <dbl>
1                         0.0854

**Comment by braverock** [comment]
PerformanceAnalytics doesn't take tibbles.  Perhaps report this on tidyquant?

    > example(AdjustedSharpeRatio)

    AdjsSR> data(portfolio_bacon)

    AdjsSR> print(AdjustedSharpeRatio(portfolio_bacon[,1])) #expected 0.7591435
                                portfolio.monthly.return....
    Annualized Sharpe Ratio (Rf=0%)                    0.7591435

    AdjsSR> data(managers)

    AdjsSR> print(AdjustedSharpeRatio(managers['1996']))
                                          HAM1    HAM2      HAM3     HAM4 HAM5 HAM6 EDHEC LS EQ SP500 TR   US 10Y TR  US 3m TR
    Adjusted Sharpe ratio (Risk free = 0) 2.045968 14.5593 0.9322736 1.883368   NA   NA          NA 1.986962 0.006312774 -576.9696

**Comment by mhmilo24** [comment]
I'm baffled. Could be a tidyquant problem, but the wrapper usually seems to work with every other risk/performance measure from PerformanceAnayltics. Thanks for the advice anyway!
