### ISSUE TITLE
DEoptim not working for portfolio weights -5 to 5

### ISSUE THREAD

**Issue by 12shivaniaggarwal** [braverock/PortfolioAnalytics#9]
I am doing portfolio optimisation maximising return per unit risk where risk is ES/ETL/CVaR using DEoptim as a solver,when I run the following lines in my portfolio:
port <- add.constraint(portfolio = port, type = "full_investment")
port <- add.constraint(portfolio = port, type = "box", min = -5, max = 5)
I get the error:
Leverage constraint min_sum and max_sum are restrictive, 
              consider relaxing. e.g. 'full_investment' constraint should be min_sum=0.99 and max_sum=1.01
Error in rp_transform(w = tportfolio, min_sum = min_sum, max_sum = max_sum,  : 
  Infeasible portfolio created, perhaps increase max_permutations and/or adjust your parameters.

Is there any solution for it?

**Comment by braverock** [comment]
Your error is happening because your constraints create an infeasible portfolio.  You aren't getting as far as DEoptim.

You can change min_sum and max_sum constraints.

But it sounds like you're trying to create a portfolio potentially levered 10x for two instruments, and possibly substantially more for multiple instruments.

So even though you can change your constraints to make it work, it seems that your portfolio model is fundamentally implausible.

**Comment by 12shivaniaggarwal** [comment]
If I want to consider the condition for short selling also, why is -5 to 5 an infeasible condition then?
It works with ROI solver easily.

I tried changing the min_sum and max_sum constraint for DEoptim, still it gave the same error.

**Comment by braverock** [comment]
-5 to +5 says that you may be short or long 500% of your capital in each asset.

This doesn't make any sense in any asset class or portfolio I can think of.

If you still can't figure out how to use the code, then provide a complete minimal reproducible example.

**Comment by 12shivaniaggarwal** [comment]
Yah, I did that because I wanted to consider the unconstrained portfolio as well, I wanted to try for different types of portfolios for my analysis.

**Comment by 12shivaniaggarwal** [comment]
library(PortfolioAnalytics)
library(DEoptim)
data(edhec)
as.names <- colnames(edhec)

as.names <- substr(x = as.names, start = 1, stop = 6) #taking first 6 c
colnames(edhec) <- as.names

port <- portfolio.spec(assets = as.names)

port <- add.constraint(portfolio = port, type = "full_investment")
#port <- add.constraint(portfolio = port, type = "long_only" )
#port <- add.constraint(portfolio = port, type = "box", min = -1, max = 1)
port <- add.constraint(portfolio = port, type = "box", min = -5, max = 5)

port <- add.objective(portfolio = port,
                      type = "risk", 
                      name="ES", 
                      arguments = list(method = "modified",p=0.95))

port <- add.objective(portfolio = port, type = "return" , name="mean")

max.sharpe1 <- optimize.portfolio(R=edhec,
                                 portfolio = port, 
                                 optimize_method = "DEoptim")
w <- max.sharpe1$weights
#The ES that we get from max.sharpe does not match the ES from x1 and x2 for ROI
port.ret <- edhec %*% w 
mean(port.ret)

x1 <- constrained_objective(w = w, edhec, portfolio = port)
x2 <- ES(R = edhec, portfolio_method = "component", weights = w)
x2<- strsplit(as.character(x2[[1]][1]),":")[[1]]
x2

**Comment by rossb34** [comment]
Based on your above code, I would not expect the solution using DEoptim to match ROI. Your portfolio specification has modified expected shortfall as an objective. Minimization of **modified** expected shortfall cannot be solved by a LP solver. Let's also be clear that you are not calculating Sharpe Ratio per the generally accepted definition... your denominator is expected shortfall, not standard deviation.

**Comment by 12shivaniaggarwal** [comment]
I am calculating Modified Sharpe Ratio, where denominator is ES, trying to match the values is not my query. 
I wanted to ask how should I optimize an unconstrained portfolio using DEoptim?

**Comment by 12shivaniaggarwal** [comment]
library(PortfolioAnalytics)
library(DEoptim)
data(edhec)
as.names <- colnames(edhec)

as.names <- substr(x = as.names, start = 1, stop = 6) #taking first 6 c
colnames(edhec) <- as.names

port <- portfolio.spec(assets = as.names)

port <- add.constraint(portfolio = port, type = "full_investment")
#port <- add.constraint(portfolio = port, type = "long_only" )
#port <- add.constraint(portfolio = port, type = "box", min = -1, max = 1)
port <- add.constraint(portfolio = port, type = "box", min = -5, max = 5)

port <- add.objective(portfolio = port,
type = "risk",
name="ES",
arguments = list(method = "modified",p=0.95))

port <- add.objective(portfolio = port, type = "return" , name="mean")

max.sharpe1 <- optimize.portfolio(R=edhec,
portfolio = port,
optimize_method = "DEoptim")

**Comment by rossb34** [comment]
The error message is telling you that your portfolio specification is over-constrained and a feasible portfolio cannot be created.
`
Leverage constraint min_sum and max_sum are restrictive,
consider relaxing. e.g. 'full_investment' constraint should be min_sum=0.99 and max_sum=1.01
`
`
Error in rp_transform(w = tportfolio, min_sum = min_sum, max_sum = max_sum,  : 
  Infeasible portfolio created, perhaps increase max_permutations and/or adjust your parameters.
`

Try relaxing constraints, first with the value (or range) the weights can sum to. DEoptim uses random portfolios algorithms to map the weights to your feasible space. In computer precision terms, getting a vector of randomly generated weights to sum **exactly** to 1 is actually quite difficult. This is why it is recommended to relax the sum of weights constraint to at least 0.99 to 1.01, maybe even 0.98 to 1.02.
`
port <- add.constraint(portfolio = port, type = "weight_sum", min_sum = 0.98, max_sum = 1.02)
`

You may also need to make your box constraints more reasonable. As has already been pointed out, allowing an asset to have a weight of +/- 500% may not be realistic.

**Comment by 12shivaniaggarwal** [comment]
If it is generating portfolios randomly, can I increase the sample space it is considering and then try the same thing?

**Comment by rossb34** [comment]
In theory, yes, but my above points still apply no matter how large your space is.

**Comment by 12shivaniaggarwal** [comment]
Okay, thank you

I faced one more issue while doing the analysis which is quite surprising.
When I used ROI for the same analysis, and then I verified the ES generated by ROI with the one generated by Perfomance Analytics, then the answer was not matching
But when I use DEoptim and do the same analysis with it, the ES generated by DEoptim and the one generated by Performance Analytics matches.

**Comment by braverock** [comment]
It seems likely that ROI found the wrong 'optimal' portfolio.  As has already been pointed out, there is no guarantee that your feasible space is smooth and convex when using modified ES.

**Comment by 12shivaniaggarwal** [comment]
So, DEoptim can be used perfectly in this situation?

**Comment by 12shivaniaggarwal** [comment]
And how to increase the sample space?
Do you suggest to increase the sample space and try the same analysis?

**Comment by braverock** [comment]
DEoptim is a global stochastic solver.  

It should find the global optima or very close to it assuming that you structure your problem correctly.  

You have already demonstrated some serious misconceptions and issues structuring your problem well.  I suggest you think hard about your constraints and objectives, and make sure that they make both technical and economic sense (+/-5 makes neither)

**Comment by 12shivaniaggarwal** [comment]
I did the analysis for 
1) portfolio having equally weighted assets
2)Long only portfolio
3)constrained -1 to 1
I also wanted to try for unconstrained that is why I did for -5 to 5. Seeing that the unconstrained does not fit well with the problem I will remove it.

**Comment by braverock** [comment]
no problem is 'unconstrained'.  it is a fiction.

most 'unconstrained' portfolio optimization problems constrain weights to 0-1 or +/-1, and impose a full investment constraint.

you don't have 10x leverage, much less 10x*n_assets, so your proposed constraint doesn't make any economic sense (or technical sense either, getting close to a full investment constraint). 

Be clear about what you're really trying to do and this all gets a lot easier (and more feasible).

**Comment by 12shivaniaggarwal** [comment]
Thank you for your valuable insight into the problem, will consider all what you said
